spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/milk_shop}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Raj anand1245}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=${PORT:8080}