spring.application.name=Main
spring.datasource.url=jdbc:mysql://localhost:3306/milk_shop

spring.datasource.username=root

spring.datasource.password=Rajanand1245

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
